// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ProductSercice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	QueryProdInfoDetail(ctx context.Context, in *ProdctInfo, opts ...grpc.CallOption) (*Response, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

var productServiceQueryProdInfoDetailStreamDesc = &grpc.StreamDesc{
	StreamName: "QueryProdInfoDetail",
}

func (c *productServiceClient) QueryProdInfoDetail(ctx context.Context, in *ProdctInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpc.product.ProductService/QueryProdInfoDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceService is the service API for ProductService service.
// Fields should be assigned to their respective handler implementations only before
// RegisterProductServiceService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type ProductServiceService struct {
	QueryProdInfoDetail func(context.Context, *ProdctInfo) (*Response, error)
}

func (s *ProductServiceService) queryProdInfoDetail(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProdctInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.QueryProdInfoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/rpc.product.ProductService/QueryProdInfoDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.QueryProdInfoDetail(ctx, req.(*ProdctInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterProductServiceService registers a service implementation with a gRPC server.
func RegisterProductServiceService(s grpc.ServiceRegistrar, srv *ProductServiceService) {
	srvCopy := *srv
	if srvCopy.QueryProdInfoDetail == nil {
		srvCopy.QueryProdInfoDetail = func(context.Context, *ProdctInfo) (*Response, error) {
			return nil, status.Errorf(codes.Unimplemented, "method QueryProdInfoDetail not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "rpc.product.ProductService",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "QueryProdInfoDetail",
				Handler:    srvCopy.queryProdInfoDetail,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "Products.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewProductServiceService creates a new ProductServiceService containing the
// implemented methods of the ProductService service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewProductServiceService(s interface{}) *ProductServiceService {
	ns := &ProductServiceService{}
	if h, ok := s.(interface {
		QueryProdInfoDetail(context.Context, *ProdctInfo) (*Response, error)
	}); ok {
		ns.QueryProdInfoDetail = h.QueryProdInfoDetail
	}
	return ns
}

// UnstableProductServiceService is the service API for ProductService service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableProductServiceService interface {
	QueryProdInfoDetail(context.Context, *ProdctInfo) (*Response, error)
}
